export const scenes = [
    { 
        bgm: {url: "Resources/BGM/LostRomance.mp3"},
        background: "Resources/IMG/EnvImg/Study.jpg", contexts: [
            { portrait: "Resources/IMG/Portrait/WuChen.png", message: "Thanh Phong, từ mai ta sẽ bế quan ba tháng, ngươi vẫn còn nhớ lời ta dặn chứ?" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Con vẫn nhớ thưa sư phụ." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Đừng mải chơi mà quên học hành..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Dù cho có xảy ra bất cứ chuyện gì, cũng không được bén mảng vào cấm địa ở hậu sơn..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Còn chăm sóc vườn hoa và vườn rau cẩn thận nữa..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Và..." },
            { portrait: "Resources/IMG/Portrait/WuChen.png", message: "..." },
            { portrait: "Resources/IMG/Portrait/WuChen.png", message: "Ừm, không tệ. Ngươi có trí nhớ tốt đấy." },
            { portrait: "Resources/IMG/Portrait/WuChen.png", message: "Ngươi rất thông minh, nhưng lại ham chơi quá mức." },
            { portrait: "Resources/IMG/Portrait/WuChen.png", message: "Nếu chú tâm tu hành, nhất định sau này sẽ được rạng danh." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Con xin nghe lời sư phụ dạy bảo." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "..." }
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Garden.jpg", contexts: [
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mình đã làm xong bài rồi, vì cớ gì mà phải tiếp tục khổ luyện chứ?" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Đời ngắn lắm, cứ tận hưởng thú vui trước đã." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Nhắc mới nhớ, cấm địa ở hậu sơn có gì mà đã phải phong ấn hàng trăm năm vậy nhỉ?" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Từ khi còn nhỏ, sư phụ đã luôn cằn nhằn mình không được bén mảng đến cấm địa đó, nói chắc cũng phải đến mấy trăm lần." }
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Sư phụ, đệ tử không phải cố ý muốn trái lời người..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...nhưng không hiểu sao mình không thể bỏ qua sự mê hoặc của cấm địa này." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Nếu không giải quyết sớm cái tâm ma này, sợ là việc tu hành sẽ rất bất lợi." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Gọi là cấm địa, nhưng sao phong ấn lại yếu ớt như vậy? Mình dùng có một phần công lực đã bị gỡ bỏ." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Hay là bởi vì trải qua trăm năm, phong ấn của tổ sư gia đã mất hiệu lực?" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Nếu đúng là vậy, thì pháp thuật của sư tổ cũng rất tầm thường..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Tội lỗi! Tội lỗi! Sao mình có thể buông những lời bất kính thế chứ?" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "..." },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Sao giờ huynh mới đến? Muội đã chờ rất lâu rồi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cương thi!! Sao lại có cương thi ở đây? Chẳng lẽ đây là thứ sư tổ phong ấn?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Đừng tới đây, nam nữ thụ thụ bất thân, chúng ta tốt nhất nên giữ khoảng cách.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương là ai? Tại sao cô lại ở đây?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Muội là ai? Chẳng lẽ huynh không nhận ra muội sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Muội đã đợi huynh rất lâu rồi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ta chắc chắn đây là lần đầu tiên chúng ta gặp nhau gặp nhau. Ta tên Thanh Phong, còn cô nương quý danh là gì?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngay cả cái tên cũng không nhớ, huynh còn đến gặp ta làm gì?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Thật là đau đầu...ả cương thi này chắc bị phong ấn quá lâu nên mụ mị rồi, nói chuyện cứ mơ mơ màng màng.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương đã bị phong ấn ở nơi này hàng trăm năm qua sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Huynh là người thả ta ra ngoài, giờ còn hỏi ta sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Xem ra ả cương thi này đúng là bị sư tổ phong ấn, e rằng chẳng phải lương thiện gì.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Để cảnh giác, tốt nhất nên tìm cơ hồi áp chế ả trước, rồi nói chuyện sau.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi không phải huynh ấy, chỉ là bề ngoài giống nhau mà thôi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta phải đi tìm huynh ấy! Tạm biệt! Cảm ơn vì đã thả ta ra.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Này...cô nương, cô không thể rời khỏi đây được.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Tại sao? Chính ngươi đã thả ta ra mà?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương hiểu lầm rồi. Ta chỉ là đến đây dạo chơi, rồi vô tình phá giải phong ấn mà thôi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mà cô lại là cương thi, vì vậy không thể rời khỏi đây được!", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cương thi...cương thi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi nói ta là cương thi? Ta không phải cương thi! Ta không phải cương thi! Ta không muốn làm cương thi!", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Chết tiệt, sao bỗng nhiên lại nổi điên như vậy? Phải dùng vũ lực áp chế ả thôi.", body: "Resources/IMG/Body/Caiyun_Body.png" }

        ]
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        battle: true,
        player: "Resources/IMG/Portrait/QingFeng.png",
        enemy: "Resources/IMG/Body/Caiyun_Body.png",
        bgm: {url: "Resources/BGM/CaiyunBattle.mp3", time: 0 },
        playerAtt: { name: "Thanh Phong", hp: 1000, atk: 100, def: 0 },
        enemyAtt: { name: "Cương thi", hp: 700, atk: 150, def: 0 }
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        bgm: {url: "Resources/BGM/LostRomance.mp3"},
        contexts: [
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Này! Cô nương đừng chạy! Nghe ta nói đã...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mặc dù thây ma khá chậm chạp, nhưng do nắm rõ địa hình sơn động nên ả đã chạy thoát..." },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Garden.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ai da, lần này phiền phức lớn rồi đây..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Bình tĩnh! Bình tĩnh nào! Kỳ thực mọi chuyện cũng chưa quá tệ." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Dựa vào cuộc trò chuyện vừa nãy, ả cũng không phải ác quỷ, chỉ là một cô nương ngớ ngẩn." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mình phải đem cô nàng trở về trước khi sư phụ xuất quan, chắc không vấn đề gì đâu nếu giữ điều đó bí mật." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mình phải lần theo dấu vết cô ta." },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Study.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "..." },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương? Làm sao cô tới được nơi này? Ta cũng đang tìm cô đây.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta theo mùi của ngươi tới đây.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mùi của ta? Sịt——Sịt——Sịt", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ồ, thật là ngại quá.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Không phải do người ngươi hôi, mà là do ta là cương thi. Cách tìm người của ta khác với người sống.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ờm...cô nương, ta không có ý mạo phạm gì đâu, nhưng cô hơi khác thường cho nên...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta chính là cương thi, ngươi nói không sai. Chỉ là do ta quá ngớ ngẩn.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Và ngươi yên tâm đi, ta rất quen thuộc với Bạch Vân Quan.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Công phu ẩn nấp của ta cũng rất cao cường, nên không sợ có người phát hiện đâu.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta tới đây là vì muốn hỏi ngươi một chuyện.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương cứ hỏi. Ta biết gì nói đấy.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có phải Minh Nguyệt phái ngươi tới thả ta ra? Huynh ấy đang ở đâu?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô biết sư tổ Minh Nguyệt? Thật đáng tiếc, ông ấy qua đời 200 năm trước rồi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Trong lúc tiến vào sơn động, có thể ta đã vô tình phá vỡ phong ấn mà thôi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Qua đời ư?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Vậy là huynh ấy đã chết từ rất lâu rồi. Ta nên biết sớm hơn mới phải.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi nhìn rất giống huynh ấy hồi nhỏ, nhưng tính cách thì hoàn toàn khác biệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Kỳ thật ta sớm nên nghĩ đến ngươi là ai.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương, ta đã 16 tuổi rồi, cũng không còn nhỏ nữa.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Nhưng nếu cô là người quen của sư tổ Minh Nguyệt...thì ta nghĩ cô nói vậy cũng đúng.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Sư phụ ngươi là ai? Ông ta có kể cho ngươi nghe về sơn động không?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Sư phụ đạo hiệu là Vô Trần, hiện là Bạch Vân Quan quán chủ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ông ấy chỉ nói rằng sơn động là khu vực cấm không ai được phép bước vào.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Vô Trần? Ta còn chẳng nhớ ra cái tên đó từ thế hệ tiểu bối nữa...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Haha, lần đầu tiên ta nghe có người gọi sư phụ đức cao vọng trọng là tiểu bối đó.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi thực sự không biết ta, và chưa nghe câu chuyện của ta?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Quả thực, ta chưa bao giờ nghe về cô cả.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta hiểu rồi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cảm ơn, giờ có lẽ ta biết ngươi muốn nói gì tiếp theo đấy.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi muốn ta trở lại sơn động và không bao giờ ra ngoài nữa, phải không?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ờm...đúng vậy, đó là lựa chọn tốt nhất cho cô nương.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Thay vì hiến tế xác của cô, sư tổ Minh Nguyệt lại phong ấn cô lại nơi đây. Ông ấy chắc chắn có suy tính lâu dài.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Suy tính của Minh Nguyệt?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngoài ta ra, ai có thể hiểu được suy nghĩ của huynh ấy?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta thực sự ước rằng ngươi đã không thả ta ra, để ta có thể có thể rơi vào giấc ngủ ngàn thu mãi mãi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nhưng mọi chuyện đã đến nước này, muội chỉ có thể kiên trì bước tiếp, phải không? Minh Nguyệt?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta hứa với ngươi ta sẽ trở về sơn động ngay lập tức và không bao giờ quay lại nữa, nhưng với một điều kiện...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương cứ nói. Ta sẽ làm tất cả khả năng để thực hiện mong muốn của cô.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta muốn ngươi về ẩn cư trong hang động cùng ta.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ẩn cư trong hang động cùng cô? Sao lại thế?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Không phải ngươi vừa mới nói điều kiện gì cũng đáp ứng sao? Sao giờ lại đổi ý rồi?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cái này...Ta phải biết tại sao chứ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Bởi vì đó là định ước giữa ta và Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cái này...những gì ta sắp nói có thể bất kính với ông ấy, nhưng sư tổ Minh Nguyệt cũng không thể vô cớ định đoạt mạng sống của ta chứ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Quyền quyết định không nằm ở ngươi. Ngươi phải đi với ta, bởi vì chính ngươi đã thả ta ra.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ờm... Không thể đổi điều kiện được sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Không được!", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Hây da! Vậy thì ta chỉ còn cách dùng vũ lực buộc cô nương về sơn động thôi, xin thứ tội!", body: "Resources/IMG/Body/Caiyun_Body.png" },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Study.jpg",
        battle: true,
        player: "Resources/IMG/Portrait/QingFeng.png",
        enemy: "Resources/IMG/Body/Caiyun_Body.png",
        bgm: {url: "Resources/BGM/CaiyunBattle.mp3", time: 0},
        playerAtt: { name: "Thanh Phong", hp: 1000, atk: 150, def: 0 },
        enemyAtt: { name: "Cương thi", hp: 1000, atk: 150, def: 0 }
    },
    {
        background: "Resources/IMG/EnvImg/Study.jpg",
        bgm: {url: "Resources/BGM/LostRomance.mp3"},
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Hây da... Sớm biết thế này thì ta đã nghe lời dốc lòng tu luyện, hiện tại đến cả tên tiểu đạo sĩ cũng không đánh nổi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ừm...thưa cô nương, mặc dù ta còn nhỏ tuổi, nhưng võ nghệ rất cao cường đó.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Vậy thì sao chứ?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Minh Nguyệt luôn nghe lời ta dù chàng có giỏi hơn ta hay không.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Kể cả sau này trở thành đệ nhất thiên hạ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta sẽ trở về sơn động trước.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nếu ngươi muốn biết nguyên nhân mọi chuyện và không muốn bị tai bay vạ gió thì hãy tới tìm ta trong sơn động.", body: "Resources/IMG/Body/Caiyun_Body.png" },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Sao giờ mới đến? Trễ thêm chút thì ta không khống chế nổi bản thân nữa rồi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô nương có chuyện gì sao? Có cần ta giúp gì không?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Để ta nói sự tình trước, lát nữa sẽ cần ngươi giúp sau.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta tên Thái Vân, và cũng là sư muội của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cái gì? Cô nương cũng là đệ tử Bạch Môn Quan sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta chẳng những là môn đệ của Bạch Môn Quan, mà còn là quán chủ tôn nữ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có thể xem là tổ cô của sư phụ Vô Trần nhà ngươi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Thật không thể tin được, ta còn nghĩ rằng cô nương chỉ có chút liên quan đến nguồn gốc Bạch Môn Quan thôi chứ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Năm ta 6 tuổi, ông ngoại ta đã đưa một đứa trẻ lang thang về làm đồ đệ trong lúc đi dạo.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Đứa trẻ đó chính là Minh Nguyệt, năm đó 16 tuổi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Mặc dù sư tổ Minh Nguyệt là đệ nhất cao thủ lúc bấy giờ, nhưng tư liệu về ông ấy không có nhiều trong thư các.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Hóa ra sư tổ lại gia nhập môn phái muộn như vậy, tư chất của ông ấy hẳn là cao lắm.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Không, huynh ấy tư chất bình thường, nhưng rất chăm chỉ. Đối với huynh ấy, ngày nào cũng chỉ biết tu luyện.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Khi huynh ấy 26 tuổi thì võ nghệ cũng cỡ ngươi bây giờ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Thanh mai trúc mã từ nhỏ nên ta với sư huynh rất thân, và bọn ta cũng gần như kết hôn khi chưa có sự cho phép của ông ngoại.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chỉ là ngoại luôn lo lắng về tư chất huynh ấy không đủ, không thể nào gánh vác trọng trách trừ ma bảo vệ môn phái.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nhưng ta chỉ nghĩ chỉ cần tốt với ta là được, quản chuyện khác làm gì?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Vì cái gì mà chúng ta luôn phải ngày đêm khổ tu, diệt trừ ác ma và bảo vệ đạo phái bằng cả tính mạng?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Tổ cô nói rất hay! Phải đem những lời này đi giáo huấn sư phụ ta mới phải.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Năm ấy bọn ta xuống núi diệt trừ tà ma cùng khác huynh muội khác.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Đó không phải nhiệm vụ khó, nhưng do sơ xuất, tình hình đã trở lên xấu đi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Trong lúc chiến đấu, ta vì cứu Minh Nguyệt mà đã bị trọng thương.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Sau đó ta được đưa về môn phái chữa trị, nhưng vô phương cứu chữa.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Minh Nguyệt tự trách bản thân và chìm trong đau khổ. Cuối cùng huynh ấy biến ta thành cương thi và giữ bí mật.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nhưng ta khác biệt so với cương thi bình thường. Ta vẫn giữ được trí nhớ và ham muốn như khi còn sống.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Mặc dù Minh Nguyệt đối xử với ta như lúc còn sống, nhưng ta vẫn là cương thi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cho nên ta không thể rời khỏi sơn động.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Chuyện này không còn ai khác biết sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ông ngoại ta biết nhưng không nói cho ai.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Vậy nghĩa là cô bất tử?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi nghĩ bất tử là tuyệt lắm sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ờm...giờ nghĩ lại...chuyện đó cũng chẳng vui lắm.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Với lại, để giữ được bộ dạng của ta cũng phải trả giá rất lớn.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ta hiểu, đó là cấm thuật, cái giá đương nhiên phải lớn. Vậy phải mất những gì?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cái giá là máu của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nghĩa là...ta phải uống máu của huynh ấy thường xuyên.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...đúng là một loại cấm thuật.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Sao tổ cô bỗng nhiên nhìn ta như vậy? Có phải ta đã nói sai gì sao?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Bởi vì ngươi chính là kiếp sau của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Tổ cô đừng nói đùa! Đừng vội khẳng định như thế chỉ vì ta trông giống sư tổ Minh Nguyệt thôi chứ.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Minh Nguyệt đã trở thành thiên hạ đệ nhất vào tuổi ba mươi, nhưng huynh ấy không hề bỏ ta và luôn đối xử tốt với ta.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Huynh ấy đem toàn bộ hậu sơn chia làm cấm địa, và ta thật hạnh phúc khi có cuộc sống đơn giản như vậy.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Năm 42 tuổi, huynh ấy đột nhiên nói rằng đã xảy ra chuyện lớn, và không thể tiếp tục đến thăm ta nữa.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta khóc rất thương tâm.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Huynh ấy từng thề sẽ không thay lòng đổi dạ, sẽ mãi yêu ta và không rời xa ta kể cả khi chết.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nhưng huynh ấy không cần thề, ta biết Minh Nguyệt luôn muốn điều tốt nhất cho ta. Huynh ấy chắc chắn có nỗi khổ tâm trong lòng.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta thương tâm vì hai năm qua khí sắc huynh ấy ngày càng kém đi. Ta sợ rằng huynh ấy sẽ tổn hao thân thể chỉ vì muốn tốt cho ta.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cuối cùng, Minh Nguyệt đem ta phong ấn lại và bố trí kết giới ngoài sơn động.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Huynh ấy nói chỉ có mình huynh ấy có thể mở được kết giới này.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nếu có một ngày ta tỉnh lại, thì đó chính là huynh ấy tới đón ta...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Thật sự ta không làm gì cả, chỉ vô tình tiến vào sơn động mà thôi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Bởi vì ngươi không làm gì cả mà phong ấn vẫn bị phá vỡ, điều đó chứng minh ngươi chính là kiếp sau của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Không...Không thể nào.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Thật ra có một biện pháp rất đơn giản để chứng minh ngươi có phải hay không.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Biện pháp gì?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta cần uống máu Minh Nguyệt thường xuyên, nếu không sẽ dần đánh mất bản trí đến khi phát cuồng và trở thành cương thi khát máu.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chỉ có máu của Minh Nguyệt mới giúp ta không biến thành như vậy.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ngươi có muốn thử không?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Không! Ta không tin! Cô chỉ đang cố gắng mê hoặc để hút máu ta mà thôi!", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Ta không có mê hoặc ngươi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "...Chỉ là ngươi không muốn chấp nhận sự thật này thôi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        battle: true,
        player: "Resources/IMG/Portrait/QingFeng.png",
        enemy: "Resources/IMG/Body/Caiyun_Body.png",
        bgm: {url: "Resources/BGM/CaiyunBattle.mp3", time: 2},
        playerAtt: { name: "Thanh Phong", hp: 1600, atk: 200, def: 0 },
        enemyAtt: { name: "Thái Vân", hp: 1800, atk: 200, def: 0 }
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        bgm: {url: "Resources/BGM/LostRomance.mp3"},
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Dù ngươi có tin hay không, đây là số mệnh luân hồi.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Không phải ngẫu nhiên mà ta với ngươi gặp nhau, đó là lời thề của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Vậy ta nên làm gì đây?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Trước khi ngươi đến, ta đã tìm ra bí pháp và bức thư mà Minh Nguyệt để lại trong sơn động.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chỉ cần làm theo những gì huynh ấy nói, là ngươi sẽ dần khôi phục pháp lực và ký ức của Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Trong mười năm tới, ngươi sẽ trở thành đệ nhất cao thủ, và ta vẫn phải ẩn cư trong hang động này.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chỉ khi nào ngươi tiến hành tam thế luân hồi, ta mới có thể khởi tử hoàn sinh...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "...và sau đó chúng ta có thể bên nhau đến đầu bạc răng long như những đôi tình nhân khác.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Cô có nghĩ ta rất ngu ngốc khi làm điều này?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Cho nên ta ước ngươi đừng phá vỡ phong ấn thì tốt biết mấy...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "...và để ta ở lại nơi ta thuộc về.", body: "Resources/IMG/Body/Caiyun_Body.png" },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Cave.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chúng ta chuẩn bị tiến hành nghi thức cuối cùng, ngươi đã sẵn sàng chưa?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Sau khi nghi thức hoàn thành, ngươi sẽ chính thức thành Minh Nguyệt và không thể trở lại như xưa nữa.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ta...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Ta...không muốn trở thành Minh Nguyệt.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Tình cảm ta dành cho nàng đang lớn dần, nhưng ta biết đó không phải cảm xúc thật sự của ta.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Đó là cảm xúc của Minh Nguyệt, chứ không phải Thanh Phong.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Hai người cố nhiên tương hữu trong lúc hoạn nạn, ngay cả sinh tử cũng không thể thay đổi điều đấy.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "Nhưng...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Nhưng điều đó thì có liên quan gì đến ngươi?", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Mặc dù là kiếp sau của Minh Nguyệt, nhưng Thanh Phong vẫn chỉ là Thanh Phong.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có lẽ ngày đó ngoại không nên thu nhận Minh Nguyệt...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có lẽ ta cũng không nên liều lĩnh cứu Minh Nguyệt bằng cả tính mạng...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có lẽ Minh Nguyệt nên học cách buông bỏ mà không phải biến ta thành cương thi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Có lẽ Minh Nguyệt nên đưa ta theo khi huynh ấy qua đời.", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Quá khứ nên để cho nó đi qua đi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Chuyện tình của Thái Vân và Minh Nguyệt đáng lẽ đã kết thúc từ 200 năm trước...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/QingFeng.png", message: "...", body: "Resources/IMG/Body/Caiyun_Body.png" },
            { portrait: "Resources/IMG/Portrait/Caiyun-Zombie.png", message: "Hãy siêu độ ta đi...", body: "Resources/IMG/Body/Caiyun_Body.png" },
        ]
    },
    {
        background: "Resources/IMG/EnvImg/Garden.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Thái Vân, nếu sư phụ phát hiện chúng ta trốn đi chơi như vậy, ông ấy sẽ..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Minh Nguyệt, trong đầu huynh chỉ nghĩ đến tu luyện thôi sao?"},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Nhưng sư phụ đã nói..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Sư phụ! Sư phụ! Trong mắt huynh chi có sư phụ, không có muội sao?"},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Giờ huynh nghe muội, hay là nghe ông của muội?"},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Ta..."},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Ta...ta...ta không biết nữa..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Huynh đúng là tên đại ngốc! Chả biết muội thích huynh ở điểm gì nữa..."},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Thái Vân, nụ cười của muội thật ngọt ngào."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Hử? Sao tự nhiên lưỡi huynh lại dẻo như thế?"},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Mau nói đi! Huynh học từ ai? Đã nói với những tỷ muội nào rồi?"},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Không! Không có ai cả! Ta không có..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Mm...vậy huynh nghĩ rằng muội rất xinh đẹp sao?"},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Phải! Chắc chắn! Chắc chắn rồi!"},
            { portrait: "Resources/IMG/Portrait/MingYue.png", message: "Thái Vân là cô gái đẹp nhất trần đời."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "..."},
        ]
    },
    {
        background: "Resources/IMG/EnvImg/CaiyunEnding_0.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Minh Nguyệt..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Mau lại đây..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Gần hơn..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Gần hơn chút nữa..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Nhắm mắt huynh lại..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Không được nhìn trộm..."},
        ]
    },
    {
        background: "Resources/IMG/EnvImg/CaiyunEnding_1.jpg",
        contexts: [
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Cúi thấp đầu xuống..."},
            { portrait: "Resources/IMG/Portrait/Caiyun.png", message: "Thấp chút nữa đi..."},
        ]
    },
    {
        ending: true,
    },
]

export const intros = [
    {
        title: "TÀ KÍNH",
        content: "Chương III: Thái Vân"
    },
    {
        title: "BẢN DỊCH",
        content: "Việt Hóa Game (Lê Hiếu)\nHội Game Á Châu (Lốp Love)"
    },
    {
        title: "",
        content: "Mọi bản quyền hình\nảnh/âm thanh thuộc về KAGAMI WORKs"
    }
]